import {
  project1Laptop,
  project1Mobile,
  project2Laptop,
  project2Mobile,
  project3Laptop,
  project3Mobile,
  project4Laptop,
  project4Mobile,
  project5Laptop,
  project5Mobile,
  project6Laptop,
  project6Mobile,
} from "./projectImages";

export const projectData = [
  {
    id: 1,
    image: project1Laptop,
    transitionImage: project1Mobile,
    title: "Zero Knowledge proof KYC",
    codeLink: "https://github.com/jdjatin/ZKP-kyc",
    // liveLink: "https://umatter.netlify.app/",
  },
  {
    id: 2,
    image: project2Laptop,
    transitionImage: project2Mobile,
    title: "Indeed scrapper",
    codeLink: "https://github.com/jdjatin/Indeed-scrapper",
    // liveLink: "https://lediable.netlify.app/",
  },
  {
    id: 3,
    image: project3Laptop,
    transitionImage: project3Mobile,
    title: "Cannabis Decentralised Loyalty App",
    codeLink: "https://github.com/jdjatin/canna_loyalty--Gateway",
    // liveLink: "https://eleganceee.netlify.app/",
  },
  {
    id: 4,
    image: project4Laptop,
    transitionImage: project4Mobile,
    title: "Forex trading application",
    codeLink: "https://github.com/jdjatin/TradingApp-NodeJs",
    // liveLink: "https://codeegrid.netlify.app/",
  },
  {
    id: 5,
    image: project5Laptop,
    transitionImage: project5Mobile,
    title: "Travel Portal",
    codeLink: "https://github.com/jdjatin/Travel-Portal",
    liveLink: "https://intrepide.netlify.app/",
  },
  {
    id: 6,
    image: project6Laptop,
    transitionImage: project6Mobile,
    title: "IP Catcher",
    codeLink: "https://github.com/jdjatin/ip_catcher",
    // liveLink: "https://spacetourism-monciego.netlify.app/",
  },
];
